# Generated by Django 6.0.4 on 2026-04-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clinicianprofile_user_alter_comment_user_and_more'),
        ('core', '0004_feedback'),
    ]

    operations = [
    ]
