# Generated by Django 5.2.13 on 2026-04-20 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_feedback_fields'),
        ('sensore', '0002_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='sensordata',
            name='core_sensor_user_id_150875_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensordata',
            name='core_sensor_timesta_5208ac_idx',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sensor_data',
        ),
        migrations.AddField(
            model_name='feedback',
            name='sensor_frame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='sensore.sensorframe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicianpatientassignment',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_assignments', to='core.clinicianprofile'),
        ),
        migrations.AlterField(
            model_name='clinicianpatientassignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='core.patientprofile'),
        ),
    ]
