# Generated by Django 4.2.30 on 2026-04-08 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_assigned_clinician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_clinician',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'clinician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
