# Generated by Django 4.2.30 on 2026-04-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clinicianprofile_user_alter_comment_user_and_more'),
        ('accounts', '0002_alter_userprofile_assigned_clinician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_clinician',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'clinician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.user'),
        ),
    ]
